baseurl = "http://www.chsmith.co.uk"
title = "Charlie Harry Smith"

theme = "coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Charlie Harry Smith"
    description = "DPhil Student at the Oxford Internet Institute"
    keywords = "blog,OII,charlieharrysmith,digital identity"
    info = "DPhil Student at the Oxford Internet Institute"
    avatarurl = "images/avatar.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = "'A good writer possesses not only his own spirit but also the spirit of his friends.' - Nietzsche"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2016

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


  [[params.social]]
      name = "ORCiD"
      icon = "fab fa-orcid"
      weight = 3
      url = "https://orcid.org/0000-0001-9832-1723"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/charliehrysmith/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://uk.linkedin.com/in/charlieharrysmith"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 4
    url = "https://medium.com/@charlieharrysmith"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 5
    url = "https://www.chsmith.co.uk/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[[params.eduction]]
        name = "Education"
        icon = "fab fa-graduation-cap"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About Me"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 3
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Research"
            weight = 2
            url = "research/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 4
            url = "contact/"
